name: imc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch==2.6.0
  - torchvision==0.21.0
  - lightglue=0.2
  - pip
  - pip:
      - lightning==2.4.0
      - faiss-cpu==1.9.0
      - pytorch-metric-learning==2.8.1
      - pandas==2.2.3
      - tensorboard==2.18.0
      - rich==13.9.4
      - scikit-learn==1.6.1
      - einops==0.8.1
      - ipython==8.35.0
      - ipykernel==6.29.5
      - einx==0.3.0
      - pycolmap==3.11.1
      - transformers==4.51.3
      - h5py==3.13.0
      - omegaconf==2.3.0

      